# Generated by Django 6.0 on 2025-12-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=20)),
                ('e', models.EmailField(max_length=254)),
                ('c', models.IntegerField()),
                ('q', models.CharField(max_length=30)),
                ('g', models.CharField(max_length=10)),
                ('s', models.CharField(max_length=20)),
                ('i', models.ImageField(upload_to='images/')),
                ('v', models.FileField(upload_to='videos/')),
                ('a', models.FileField(upload_to='audio/')),
                ('f', models.FileField(upload_to='fields/')),
            ],
        ),
    ]
