# Generated by Django 6.0 on 2025-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='a',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='c',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='g',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='i',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='n',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='q',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='s',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='v',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='f',
        ),
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(default='temp/placeholder.txt', upload_to='documents/'),
        ),
    ]
