# Generated by Django 6.0 on 2025-12-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_a_employee_audio_rename_c_employee_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
