# Generated by Django 6.0 on 2026-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_department_employee1'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
