# Generated by Django 6.0 on 2026-01-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee1',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
