# Generated by Django 6.0 on 2026-01-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userquery_employee1_d_code_employee1_d_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
