# Generated by Django 6.0 on 2026-01-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_query_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
