# Generated by Django 6.0 on 2026-01-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_userquery_query_created_at_query_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='solution',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
